variable "teamid" {
  description = "(Required) Name of the team/group e.g. devops, dataengineering. Should not be changed after running 'tf apply'"
}

variable "prjid" {
  description = "(Required) Name of the project/stack e.g: mystack, nifieks, demoaci. Should not be changed after running 'tf apply'"
}

variable "profile_to_use" {
  description = "Getting values from ~/.aws/credentials"
  default     = "default"
}

variable "performance_mode" {
  description = "The performance mode of your file system."
  default     = "generalPurpose"
}

variable "throughput_mode" {
  description = "Throughput mode for the file system. Defaults to bursting. Valid values: bursting, provisioned. When using provisioned, also set provisioned_throughput_in_mibps."
  default     = "bursting"
}

variable "security_groups_to_use" {
  description = "Security Groups"
  type        = list(any)
}

variable "encrypted" {
  description = "The disk will be encrypted"
  default     = true
}

variable "kms_key_id" {
  description = "The ARN for the KMS encryption key. When specifying kms_key_id, encrypted needs to be set to true."
  default     = ""
}

variable "account_id" {
  description = "AWS account id (used to pull values from shared base module like vpc info, subnet ids)"
}

variable "aws_region" {
  default = "us-west-2"
}

variable "deploy_efs" {
  description = "feature flag, true or false"
  default     = true
  type        = bool
}

variable "subnets" {
  default     = []
  description = "Subnet IDs that the EFS mount points should be created on (required if `create==true`)"
  type        = list(string)
}

variable "transition_to_ia" {
  description = "Indicates how long it takes to transition files to the IA storage class. Valid values: AFTER_7_DAYS, AFTER_14_DAYS, AFTER_30_DAYS, AFTER_60_DAYS and AFTER_90_DAYS"
  default     = ""
}

variable "mount_target_ip_address" {
  description = "The address (within the address range of the specified subnet) at which the file system may be mounted via the mount target"
  default     = null
}

variable "access_points" {
  type        = map(map(map(any)))
  default     = {}
  description = "A map of the access points you would like in your EFS volume"
}

variable "name" {
  description = "A unique name (a maximum of 64 characters are allowed) used as reference when creating the Elastic File System to ensure idempotent file system creation. By default generated by Terraform. See [Elastic File System] (http://docs.aws.amazon.com/efs/latest/ug/) user guide for more information."
  default     = null
}

variable "provisioned_throughput" {
  default     = null
  description = "Provisioned throughput (in mbps)"
}