variable "performance_mode" {
  description = "The performance mode of your file system."
  default     = "generalPurpose"
  type        = string
}

variable "throughput_mode" {
  description = "Throughput mode for the file system. Defaults to bursting. Valid values: bursting, provisioned. When using provisioned, also set provisioned_throughput_in_mibps."
  default     = "bursting"
  type        = string
}

variable "security_groups" {
  description = "Security Groups"
  type        = list(any)
}

variable "encrypted" {
  description = "The disk will be encrypted"
  default     = true
  type        = bool
}

variable "kms_key_id" {
  description = "The ARN for the KMS encryption key. When specifying kms_key_id, encrypted needs to be set to true."
  default     = ""
  type        = string
}

variable "deploy_efs" {
  description = "Feature flag, true or false"
  default     = true
  type        = bool
}

variable "efs_mount_target" {
  description = "Feature flag, true or false"
  default     = true
  type        = bool
}

variable "transition_to_ia" {
  description = "Indicates how long it takes to transition files to the IA storage class. Valid values: AFTER_7_DAYS, AFTER_14_DAYS, AFTER_30_DAYS, AFTER_60_DAYS and AFTER_90_DAYS"
  default     = ""
  type        = string
}

variable "mount_target_ip_address" {
  description = "The address (within the address range of the specified subnet) at which the file system may be mounted via the mount target"
  default     = null
  type        = string
}

variable "access_points" {
  type        = map(map(map(any)))
  default     = {}
  description = "A map of the access points you would like in your EFS volume"
}

variable "name" {
  description = "A unique name (a maximum of 64 characters are allowed) used as reference when creating the Elastic File System to ensure idempotent file system creation. By default generated by Terraform. See [Elastic File System] (http://docs.aws.amazon.com/efs/latest/ug/) user guide for more information"
  default     = null
  type        = string
}

variable "provisioned_throughput" {
  default     = null
  description = "Provisioned throughput (in mbps)"
  type        = string
}

variable "file_system_id" {
  description = "The ID of the file system for which the mount target is intended"
  default     = null
  type        = string
}
